changelog:
  enabled: true
  pattern: '^[A-Z].{19,}'
  template: |
    {{range .Commits}}- {{ .Message }}
    {{end}}

build:
  zip:
    pack:
      excludes:
        paths:
          - docs
          - TODO.md
